[package]
name = "disconnect"
version.workspace = true
edition.workspace = true

[dependencies]
tokio.workspace = true
lambda_runtime.workspace = true
lambda_http.workspace = true
serde_json.workspace = true
